export interface studentProps {
  studentId?:string,
  name?: string,
  cpf?: string,
  data_nascimento?: string,
  responsavel_nome?: string,
  responsavel_vinculo?: string,
  telefone_contato?: string,
  telefone_emergencia?: string,
  foto?: any,
  vacina?: any,
  rg_frente?: any,
  rg_verso?: any,
  residencia?: any,
  cardiologista?: any,
  dermatologista?: any,
  courseId?:string[],
}
